---
language: python
python:
  - "3.7"
services:
  - docker
install:
  - pip install molecule docker
  - travis_wait 30 molecule test
script:
  - molecule --version
  - ansible --version
  - molecule test