---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: "${image}-${tag}"
    image: "${image}:${tag}"
    command: /sbin/init
    groups:
      - "${image}"
    privileged: true
    env: 
      http_proxy: "${http_proxy}"
      https_proxy: "${https_proxy}"
      no_proxy: "${no_proxy}"
      mirror: "${mirror}"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
