---
name: Molecule Test
on: 
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches: 
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        image: [debian]
        tag: [buster,stretch]
    steps:
      - uses: actions/checkout@v1
        with:
          path: ansible-role-samba
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt install docker
          python -m pip install --upgrade pip
          pip install ansible molecule pytest docker
      - name: Test with molecule
        run: molecule test
        env:
          image: ${{ matrix.image }}
          tag: ${{ matrix.tag }}  
